import type { AnalysisResult } from './types'

export const SAMPLE_CANCELLATION_RESULT: AnalysisResult = {
  originalText:
    'Customer may cancel the booking by giving written notice at least 14 days before the scheduled service date. If Customer cancels within the required period, Provider will refund 50% of fees already paid, excluding non-recoverable third-party costs. No refund will be provided for cancellations made fewer than 14 days before the service date, except where cancellation is caused by a force majeure event. For purposes of this clause, force majeure means an event beyond the reasonable control of the affected party, including natural disaster, government order, or widespread service outage.',
  originalBlocks: [
    {
      id: 'o1',
      text: 'Customer may cancel the booking by giving written notice at least 14 days before the scheduled service date.',
    },
    {
      id: 'o2',
      text: 'If Customer cancels within the required period, Provider will refund 50% of fees already paid, excluding non-recoverable third-party costs.',
    },
    {
      id: 'o3',
      text: 'No refund will be provided for cancellations made fewer than 14 days before the service date, except where cancellation is caused by a force majeure event.',
    },
    {
      id: 'o4',
      text: 'For purposes of this clause, force majeure means an event beyond the reasonable control of the affected party, including natural disaster, government order, or widespread service outage.',
    },
  ],
  levels: [
    {
      level: 0,
      blocks: [
        {
          id: 'l0-b1',
          level: 0,
          sourceBlockIds: ['o1'],
          text: 'Customer may cancel the booking by giving written notice at least 14 days before the scheduled service date.',
          fidelityNoteIds: [],
          termIds: ['t1', 't2'],
        },
        {
          id: 'l0-b2',
          level: 0,
          sourceBlockIds: ['o2'],
          text: 'If Customer cancels within the required period, Provider will refund 50% of fees already paid, excluding non-recoverable third-party costs.',
          fidelityNoteIds: [],
          termIds: ['t3'],
        },
        {
          id: 'l0-b3',
          level: 0,
          sourceBlockIds: ['o3'],
          text: 'No refund will be provided for cancellations made fewer than 14 days before the service date, except where cancellation is caused by a force majeure event.',
          fidelityNoteIds: [],
          termIds: ['t4'],
        },
        {
          id: 'l0-b4',
          level: 0,
          sourceBlockIds: ['o4'],
          text: 'Force majeure means an event beyond the reasonable control of the affected party, including natural disaster, government order, or widespread service outage.',
          fidelityNoteIds: [],
          termIds: ['t4', 't5'],
        },
      ],
    },
    {
      level: 1,
      blocks: [
        {
          id: 'l1-b1',
          level: 1,
          sourceBlockIds: ['o1'],
          text: 'Customer can cancel by sending written notice at least 14 days before the service date.',
          fidelityNoteIds: ['n1'],
          termIds: ['t1', 't2'],
        },
        {
          id: 'l1-b2',
          level: 1,
          sourceBlockIds: ['o2'],
          text: 'If cancellation is on time, Provider refunds 50% of fees already paid, but not non-recoverable third-party costs.',
          fidelityNoteIds: ['n2'],
          termIds: ['t3'],
        },
        {
          id: 'l1-b3',
          level: 1,
          sourceBlockIds: ['o3', 'o4'],
          text: 'Late cancellations receive no refund unless a force majeure event caused the cancellation.',
          fidelityNoteIds: ['n3'],
          termIds: ['t4'],
        },
        {
          id: 'l1-b4',
          level: 1,
          sourceBlockIds: ['o4'],
          text: 'Force majeure covers events beyond a party\'s reasonable control, such as disasters, government orders, or major outages.',
          fidelityNoteIds: ['n4'],
          termIds: ['t4', 't5'],
        },
      ],
    },
    {
      level: 2,
      blocks: [
        {
          id: 'l2-b1',
          level: 2,
          sourceBlockIds: ['o1', 'o2'],
          text: 'Cancel at least 14 days before the service date to receive a 50% refund, except for certain third-party costs.',
          fidelityNoteIds: ['n5', 'n6'],
          termIds: ['t1', 't3'],
        },
        {
          id: 'l2-b2',
          level: 2,
          sourceBlockIds: ['o3'],
          text: 'Canceling later than 14 days usually means no refund.',
          fidelityNoteIds: ['n7'],
          termIds: [],
        },
        {
          id: 'l2-b3',
          level: 2,
          sourceBlockIds: ['o3', 'o4'],
          text: 'The main exception is a force majeure event, such as a disaster, government order, or widespread outage.',
          fidelityNoteIds: ['n8'],
          termIds: ['t4', 't5'],
        },
      ],
    },
    {
      level: 3,
      blocks: [
        {
          id: 'l3-b1',
          level: 3,
          sourceBlockIds: ['o1', 'o2', 'o3'],
          text: 'Cancel early for a partial refund; cancel late and there is usually no refund.',
          fidelityNoteIds: ['n9', 'n10'],
          termIds: ['t3'],
        },
        {
          id: 'l3-b2',
          level: 3,
          sourceBlockIds: ['o3', 'o4'],
          text: 'A serious outside event may create an exception.',
          fidelityNoteIds: ['n11'],
          termIds: ['t4'],
        },
      ],
    },
  ],
  fidelityNotes: [
    {
      id: 'n1',
      blockId: 'l1-b1',
      level: 1,
      type: 'Notice Requirement Simplified',
      severity: 'low',
      message: 'Written notice is kept, but the exact phrase "scheduled service date" is shortened.',
      whyItMatters: 'The timing trigger still matters for whether cancellation is on time.',
    },
    {
      id: 'n2',
      blockId: 'l1-b2',
      level: 1,
      type: 'Liability Detail Compressed',
      severity: 'low',
      message: 'The refund formula and third-party cost exclusion are restated in plainer terms.',
      whyItMatters: 'Excluded costs can reduce the amount actually refunded.',
    },
    {
      id: 'n3',
      blockId: 'l1-b3',
      level: 1,
      type: 'Exception Compressed',
      severity: 'medium',
      message: 'The late-cancellation exception is merged with the no-refund rule.',
      whyItMatters: 'The exception changes the outcome for some late cancellations.',
    },
    {
      id: 'n4',
      blockId: 'l1-b4',
      level: 1,
      type: 'Legal Term Generalized',
      severity: 'low',
      message: 'Force majeure is explained with examples rather than the full definition wording.',
      whyItMatters: 'The listed examples do not cover every possible qualifying event.',
    },
    {
      id: 'n5',
      blockId: 'l2-b1',
      level: 2,
      type: 'Condition Compressed',
      severity: 'medium',
      message: 'The cancellation deadline and refund condition are combined into one sentence.',
      whyItMatters: 'Users should inspect the original to see the exact notice requirement.',
    },
    {
      id: 'n6',
      blockId: 'l2-b1',
      level: 2,
      type: 'Liability Detail Compressed',
      severity: 'medium',
      message: 'Non-recoverable third-party costs are summarized as certain third-party costs.',
      whyItMatters: 'The precise cost category affects the refund amount.',
    },
    {
      id: 'n7',
      blockId: 'l2-b2',
      level: 2,
      type: 'Exception Omitted',
      severity: 'high',
      message: 'The force majeure exception is not included in this block.',
      whyItMatters: 'A user reading only this block could miss a possible exception.',
    },
    {
      id: 'n8',
      blockId: 'l2-b3',
      level: 2,
      type: 'Legal Term Generalized',
      severity: 'medium',
      message: 'Force majeure is described by examples and a simplified label.',
      whyItMatters: 'The original definition controls the exact scope of the exception.',
    },
    {
      id: 'n9',
      blockId: 'l3-b1',
      level: 3,
      type: 'Timing Detail Simplified',
      severity: 'high',
      message: 'The 14-day deadline is replaced with "early" and "late."',
      whyItMatters: 'The exact number of days is necessary to apply the clause.',
    },
    {
      id: 'n10',
      blockId: 'l3-b1',
      level: 3,
      type: 'Condition Omitted',
      severity: 'high',
      message: 'Written notice and third-party cost exclusions are omitted from the gist.',
      whyItMatters: 'Those details affect whether cancellation is valid and how much is refunded.',
    },
    {
      id: 'n11',
      blockId: 'l3-b2',
      level: 3,
      type: 'Legal Term Generalized',
      severity: 'medium',
      message: 'Force majeure is generalized as a serious outside event.',
      whyItMatters: 'The original definition is narrower than ordinary hardship.',
    },
  ],
  terms: [
    {
      id: 't1',
      term: 'written notice',
      sourceBlockId: 'o1',
      plainExplanation: 'A cancellation message that must be provided in writing.',
      whyItMatters: 'The method of notice may affect whether cancellation counts under the clause.',
      example: 'An email may count only if the contract treats email as written notice.',
    },
    {
      id: 't2',
      term: 'scheduled service date',
      sourceBlockId: 'o1',
      plainExplanation: 'The date the service is planned to happen.',
      whyItMatters: 'The cancellation deadline is measured backward from this date.',
      example: 'If service is on June 30, a 14-day deadline points to June 16.',
    },
    {
      id: 't3',
      term: 'non-recoverable third-party costs',
      sourceBlockId: 'o2',
      plainExplanation: 'Costs paid to others that the provider cannot get back.',
      whyItMatters: 'These costs may be excluded from the customer\'s refund.',
      example: 'A venue deposit that cannot be refunded by the venue.',
    },
    {
      id: 't4',
      term: 'force majeure',
      sourceBlockId: 'o3',
      plainExplanation: 'A major outside event beyond a party\'s reasonable control.',
      whyItMatters: 'It can create an exception to the no-refund rule.',
      example: 'A government order that prevents the service from occurring.',
    },
    {
      id: 't5',
      term: 'reasonable control',
      sourceBlockId: 'o4',
      plainExplanation: 'What a party could realistically prevent or manage.',
      whyItMatters: 'The exception depends on whether the event was outside that control.',
      example: 'A widespread outage may be outside control; poor scheduling may not be.',
    },
  ],
}

export const SAMPLE_SUBSCRIPTION_RESULT: AnalysisResult = {
  originalText:
    'The subscription will automatically renew for successive monthly terms unless Subscriber cancels at least 7 days before the renewal date. Cancellation must be submitted through the account portal or by email to support@example.com. Fees already paid are non-refundable, including fees for the then-current billing period. After cancellation, Subscriber will retain account access until the end of the paid billing period, unless access is suspended earlier for violation of this Agreement.',
  originalBlocks: [
    {
      id: 'o1',
      text: 'The subscription will automatically renew for successive monthly terms unless Subscriber cancels at least 7 days before the renewal date.',
    },
    {
      id: 'o2',
      text: 'Cancellation must be submitted through the account portal or by email to support@example.com.',
    },
    {
      id: 'o3',
      text: 'Fees already paid are non-refundable, including fees for the then-current billing period.',
    },
    {
      id: 'o4',
      text: 'After cancellation, Subscriber will retain account access until the end of the paid billing period, unless access is suspended earlier for violation of this Agreement.',
    },
  ],
  levels: [
    {
      level: 0,
      blocks: [
        {
          id: 'l0-b1',
          level: 0,
          sourceBlockIds: ['o1'],
          text: 'The subscription automatically renews for successive monthly terms unless Subscriber cancels at least 7 days before the renewal date.',
          fidelityNoteIds: [],
          termIds: ['t1', 't2'],
        },
        {
          id: 'l0-b2',
          level: 0,
          sourceBlockIds: ['o2'],
          text: 'Cancellation must be submitted through the account portal or by email to support@example.com.',
          fidelityNoteIds: [],
          termIds: ['t3'],
        },
        {
          id: 'l0-b3',
          level: 0,
          sourceBlockIds: ['o3'],
          text: 'Fees already paid are non-refundable, including fees for the then-current billing period.',
          fidelityNoteIds: [],
          termIds: ['t4'],
        },
        {
          id: 'l0-b4',
          level: 0,
          sourceBlockIds: ['o4'],
          text: 'After cancellation, Subscriber keeps account access until the end of the paid billing period, unless access is suspended earlier for violation of this Agreement.',
          fidelityNoteIds: [],
          termIds: ['t5'],
        },
      ],
    },
    {
      level: 1,
      blocks: [
        {
          id: 'l1-b1',
          level: 1,
          sourceBlockIds: ['o1'],
          text: 'The subscription renews each month unless Subscriber cancels at least 7 days before renewal.',
          fidelityNoteIds: ['n1'],
          termIds: ['t1', 't2'],
        },
        {
          id: 'l1-b2',
          level: 1,
          sourceBlockIds: ['o2'],
          text: 'Subscriber must cancel through the account portal or by emailing support@example.com.',
          fidelityNoteIds: ['n2'],
          termIds: ['t3'],
        },
        {
          id: 'l1-b3',
          level: 1,
          sourceBlockIds: ['o3'],
          text: 'Payments already made are not refundable, including the current billing period.',
          fidelityNoteIds: ['n3'],
          termIds: ['t4'],
        },
        {
          id: 'l1-b4',
          level: 1,
          sourceBlockIds: ['o4'],
          text: 'After cancellation, access continues through the paid period unless the account is suspended earlier for an agreement violation.',
          fidelityNoteIds: ['n4'],
          termIds: ['t5'],
        },
      ],
    },
    {
      level: 2,
      blocks: [
        {
          id: 'l2-b1',
          level: 2,
          sourceBlockIds: ['o1', 'o2'],
          text: 'Cancel at least 7 days before renewal using the portal or support email to stop the next monthly renewal.',
          fidelityNoteIds: ['n5', 'n6'],
          termIds: ['t1', 't2', 't3'],
        },
        {
          id: 'l2-b2',
          level: 2,
          sourceBlockIds: ['o3'],
          text: 'Already-paid subscription fees are not refunded.',
          fidelityNoteIds: ['n7'],
          termIds: ['t4'],
        },
        {
          id: 'l2-b3',
          level: 2,
          sourceBlockIds: ['o4'],
          text: 'Access normally lasts until the paid period ends, but may end earlier after an agreement violation.',
          fidelityNoteIds: ['n8'],
          termIds: ['t5'],
        },
      ],
    },
    {
      level: 3,
      blocks: [
        {
          id: 'l3-b1',
          level: 3,
          sourceBlockIds: ['o1', 'o2'],
          text: 'Cancel before the renewal deadline, using an allowed notice method, to stop the next month.',
          fidelityNoteIds: ['n9', 'n10'],
          termIds: ['t2', 't3'],
        },
        {
          id: 'l3-b2',
          level: 3,
          sourceBlockIds: ['o3', 'o4'],
          text: 'Past payments are not refunded, and access usually continues only through the paid period.',
          fidelityNoteIds: ['n11', 'n12'],
          termIds: ['t4', 't5'],
        },
      ],
    },
  ],
  fidelityNotes: [
    {
      id: 'n1',
      blockId: 'l1-b1',
      level: 1,
      type: 'Timing Detail Simplified',
      severity: 'low',
      message: 'The phrase "successive monthly terms" is simplified to renews each month.',
      whyItMatters: 'The renewal cycle determines when the cancellation deadline applies.',
    },
    {
      id: 'n2',
      blockId: 'l1-b2',
      level: 1,
      type: 'Notice Requirement Simplified',
      severity: 'low',
      message: 'The allowed notice methods are restated in direct language.',
      whyItMatters: 'Using another method may not satisfy the clause.',
    },
    {
      id: 'n3',
      blockId: 'l1-b3',
      level: 1,
      type: 'Meaning Preserved',
      severity: 'info',
      message: 'The non-refundable payment rule is kept with minimal wording changes.',
      whyItMatters: 'This rule explains the payment consequence of cancellation.',
    },
    {
      id: 'n4',
      blockId: 'l1-b4',
      level: 1,
      type: 'Exception Compressed',
      severity: 'medium',
      message: 'The early suspension exception is shortened.',
      whyItMatters: 'Access may end earlier if the violation condition applies.',
    },
    {
      id: 'n5',
      blockId: 'l2-b1',
      level: 2,
      type: 'Condition Compressed',
      severity: 'medium',
      message: 'Renewal timing, cancellation deadline, and notice methods are combined.',
      whyItMatters: 'Each condition must be checked separately in the original text.',
    },
    {
      id: 'n6',
      blockId: 'l2-b1',
      level: 2,
      type: 'Notice Requirement Simplified',
      severity: 'medium',
      message: 'The exact email address is summarized as support email.',
      whyItMatters: 'The specific address may matter for valid cancellation.',
    },
    {
      id: 'n7',
      blockId: 'l2-b2',
      level: 2,
      type: 'Liability Detail Compressed',
      severity: 'medium',
      message: 'The current billing period detail is folded into already-paid fees.',
      whyItMatters: 'The original clarifies that the current period is included.',
    },
    {
      id: 'n8',
      blockId: 'l2-b3',
      level: 2,
      type: 'Exception Compressed',
      severity: 'medium',
      message: 'The agreement violation exception is simplified.',
      whyItMatters: 'The exception affects continued account access.',
    },
    {
      id: 'n9',
      blockId: 'l3-b1',
      level: 3,
      type: 'Timing Detail Simplified',
      severity: 'high',
      message: 'The exact 7-day deadline is described as the renewal deadline.',
      whyItMatters: 'The number of days is needed to apply the clause.',
    },
    {
      id: 'n10',
      blockId: 'l3-b1',
      level: 3,
      type: 'Notice Requirement Simplified',
      severity: 'high',
      message: 'The portal and email address are generalized as allowed notice methods.',
      whyItMatters: 'The user must inspect the original for the permitted methods.',
    },
    {
      id: 'n11',
      blockId: 'l3-b2',
      level: 3,
      type: 'Liability Detail Compressed',
      severity: 'medium',
      message: 'The non-refundable rule and access rule are merged.',
      whyItMatters: 'Payment and access are separate consequences.',
    },
    {
      id: 'n12',
      blockId: 'l3-b2',
      level: 3,
      type: 'Exception Omitted',
      severity: 'high',
      message: 'The earlier suspension exception is not stated in this gist block.',
      whyItMatters: 'The account may lose access before the paid period ends.',
    },
  ],
  terms: [
    {
      id: 't1',
      term: 'automatic renewal',
      sourceBlockId: 'o1',
      plainExplanation: 'The subscription continues into a new term without a new purchase step.',
      whyItMatters: 'The subscriber may be charged again unless cancellation happens on time.',
      example: 'A monthly plan renews for another month on the renewal date.',
    },
    {
      id: 't2',
      term: 'renewal date',
      sourceBlockId: 'o1',
      plainExplanation: 'The date when the next subscription period starts.',
      whyItMatters: 'The cancellation deadline is measured before this date.',
      example: 'If renewal is May 10, a 7-day deadline points to May 3.',
    },
    {
      id: 't3',
      term: 'account portal',
      sourceBlockId: 'o2',
      plainExplanation: 'The online account area where cancellation can be submitted.',
      whyItMatters: 'It is one of the approved cancellation methods.',
      example: 'A billing settings page with a cancellation control.',
    },
    {
      id: 't4',
      term: 'non-refundable',
      sourceBlockId: 'o3',
      plainExplanation: 'Money already paid will not be returned under this clause.',
      whyItMatters: 'It explains the financial result after cancellation.',
      example: 'Canceling mid-month does not return the monthly fee already paid.',
    },
    {
      id: 't5',
      term: 'paid billing period',
      sourceBlockId: 'o4',
      plainExplanation: 'The subscription time span that has already been paid for.',
      whyItMatters: 'It sets how long access continues after cancellation.',
      example: 'A user who paid through June 30 keeps access until June 30 unless suspended.',
    },
  ],
}
